[package]
name = "icydb-core"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
license = { workspace = true }
description = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }

[lib]
doctest = false

[dependencies]
candid = { workspace = true }
canic-cdk = { workspace = true }
canic-utils = { workspace = true }
chrono = { workspace = true }
derive_more = { workspace = true }
num-traits = { workspace = true }
rust_decimal = { workspace = true }
serde = { workspace = true }
serde_cbor = { workspace = true }
serde_bytes = { workspace = true }
thiserror = { workspace = true }
ulid = { workspace = true }

[dev-dependencies]
bencher = "0.1"
serde_json = "1.0"

[lints]
workspace = true

[[bench]]
name = "all"
path = "benches/all.rs"
harness = false
